package in.supporthub.ai.dto;

/**
 * A single resolution suggestion generated by the AI for a support agent.
 *
 * @param title      Short title of the suggested resolution template (e.g., "Refund Issued").
 * @param content    Full text of the suggested response the agent can send to the customer.
 * @param confidence Confidence score from 0.0 to 1.0 indicating how relevant this suggestion is.
 */
public record ResolutionSuggestion(
        String title,
        String content,
        double confidence) {}
