-- ============================================================
-- V1: (no-op) tenants table is owned by tenant-service
-- The tenants table is created by tenant-service V1 migration.
-- auth-service references tenant_id as a UUID FK only and does
-- not own the tenants table schema.
-- ============================================================
-- This migration intentionally empty to preserve version numbering.
