import type { TicketSummary, TicketDetail, TicketActivity, ResolutionSuggestion, DashboardMetrics, Notification, CustomerProfile, Category } from './ticketApi.js';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Order Issues', slug: 'order-issues' },
  { id: 'cat-2', name: 'Delivery Problems', slug: 'delivery-problems' },
  { id: 'cat-3', name: 'Refund & Payments', slug: 'refund-payments' },
  { id: 'cat-4', name: 'Wrong Item', slug: 'wrong-item' },
  { id: 'cat-5', name: 'App/Technical', slug: 'app-technical' },
  { id: 'cat-6', name: 'Restaurant Complaint', slug: 'restaurant-complaint' },
];

export const MOCK_TICKETS: TicketSummary[] = [
  {
    id: 'tkt-001',
    ticketNumber: 'TKT-2024-001',
    title: 'Order not delivered — 2 hours past ETA',
    status: 'OPEN',
    priority: 'URGENT',
    customerName: 'Rahul Sharma',
    assignedAgentId: null,
    categoryName: 'Delivery Problems',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    slaBreached: true,
    sentimentLabel: 'very_negative',
    channel: 'WEB',
    tags: ['delivery', 'urgent'],
  },
  {
    id: 'tkt-002',
    ticketNumber: 'TKT-2024-002',
    title: 'Wrong item received — ordered chicken biryani, got veg pulao',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    customerName: 'Priya Nair',
    assignedAgentId: 'agent-me',
    categoryName: 'Wrong Item',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    slaBreached: false,
    sentimentLabel: 'negative',
    channel: 'APP',
    tags: ['wrong-item', 'refund-requested'],
  },
  {
    id: 'tkt-003',
    ticketNumber: 'TKT-2024-003',
    title: 'Refund not received after 7 days',
    status: 'ESCALATED',
    priority: 'HIGH',
    customerName: 'Amit Patel',
    assignedAgentId: 'agent-me',
    categoryName: 'Refund & Payments',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    slaBreached: true,
    sentimentLabel: 'very_negative',
    channel: 'WHATSAPP',
    tags: ['refund', 'escalated'],
  },
  {
    id: 'tkt-004',
    ticketNumber: 'TKT-2024-004',
    title: 'Food arrived cold and packaging was damaged',
    status: 'OPEN',
    priority: 'MEDIUM',
    customerName: 'Sneha Reddy',
    assignedAgentId: null,
    categoryName: 'Restaurant Complaint',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    slaBreached: false,
    sentimentLabel: 'negative',
    channel: 'WEB',
    tags: ['quality', 'packaging'],
  },
  {
    id: 'tkt-005',
    ticketNumber: 'TKT-2024-005',
    title: 'App crash during payment — amount debited but order not placed',
    status: 'OPEN',
    priority: 'URGENT',
    customerName: 'Kiran Mehta',
    assignedAgentId: null,
    categoryName: 'App/Technical',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    slaBreached: false,
    sentimentLabel: 'very_negative',
    channel: 'APP',
    tags: ['payment', 'technical', 'urgent'],
  },
  {
    id: 'tkt-006',
    ticketNumber: 'TKT-2024-006',
    title: 'Promo code not applied to order',
    status: 'PENDING_CUSTOMER_RESPONSE',
    priority: 'LOW',
    customerName: 'Deepa Krishnan',
    assignedAgentId: 'agent-me',
    categoryName: 'Order Issues',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    slaBreached: false,
    sentimentLabel: 'neutral',
    channel: 'APP',
    tags: ['promo', 'billing'],
  },
  {
    id: 'tkt-007',
    ticketNumber: 'TKT-2024-007',
    title: 'Partial order received — 2 items missing from delivery',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    customerName: 'Vijay Kumar',
    assignedAgentId: 'agent-me',
    categoryName: 'Order Issues',
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    slaBreached: false,
    sentimentLabel: 'negative',
    channel: 'WEB',
    tags: ['missing-items', 'partial-delivery'],
  },
  {
    id: 'tkt-008',
    ticketNumber: 'TKT-2024-008',
    title: 'Delivery partner was rude and unprofessional',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    customerName: 'Ananya Singh',
    assignedAgentId: 'agent-other',
    categoryName: 'Delivery Problems',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    slaBreached: false,
    sentimentLabel: 'negative',
    channel: 'APP',
    tags: ['delivery-partner', 'resolved'],
  },
  {
    id: 'tkt-009',
    ticketNumber: 'TKT-2024-009',
    title: 'Unable to track order — location not updating',
    status: 'OPEN',
    priority: 'MEDIUM',
    customerName: 'Ravi Shankar',
    assignedAgentId: null,
    categoryName: 'App/Technical',
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    slaBreached: false,
    sentimentLabel: 'neutral',
    channel: 'WEB',
    tags: ['tracking', 'technical'],
  },
  {
    id: 'tkt-010',
    ticketNumber: 'TKT-2024-010',
    title: 'Duplicate charge on my credit card',
    status: 'ESCALATED',
    priority: 'HIGH',
    customerName: 'Sunita Agarwal',
    assignedAgentId: null,
    categoryName: 'Refund & Payments',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    slaBreached: true,
    sentimentLabel: 'very_negative',
    channel: 'WHATSAPP',
    tags: ['payment', 'duplicate-charge'],
  },
  {
    id: 'tkt-011',
    ticketNumber: 'TKT-2024-011',
    title: 'Restaurant cancelled order without notice',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    customerName: 'Pooja Iyer',
    assignedAgentId: 'agent-other',
    categoryName: 'Order Issues',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    slaBreached: false,
    sentimentLabel: 'negative',
    channel: 'APP',
    tags: ['cancellation', 'resolved'],
  },
  {
    id: 'tkt-012',
    ticketNumber: 'TKT-2024-012',
    title: 'Cashback not credited for qualifying order',
    status: 'OPEN',
    priority: 'LOW',
    customerName: 'Manoj Gupta',
    assignedAgentId: null,
    categoryName: 'Refund & Payments',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    slaBreached: false,
    sentimentLabel: 'neutral',
    channel: 'WEB',
    tags: ['cashback', 'billing'],
  },
];

export const MOCK_TICKET_DETAILS: Record<string, TicketDetail> = {
  'TKT-2024-001': {
    ...MOCK_TICKETS[0],
    description: 'I placed an order at 6:30 PM (Order #ORD-789456). The app showed estimated delivery at 7:15 PM. It is now 9:20 PM and I have not received my order. The delivery partner\'s phone is not reachable. I have been waiting for 2 hours and my family is hungry. This is completely unacceptable. I want an immediate resolution or full refund.',
    channel: 'WEB',
    customerId: 'cust-001',
    subCategoryName: 'Late Delivery',
    orderId: 'ORD-789456',
    tags: ['delivery', 'urgent', 'sla-breach'],
    firstResponseDeadline: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    resolutionDeadline: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
    customerPhone: '+91 98765 43210',
    customerEmail: null,
    totalTickets: 3,
  },
  'TKT-2024-002': {
    ...MOCK_TICKETS[1],
    description: 'I ordered Chicken Biryani (1 plate) + Garlic Naan (2 pcs) + Gulab Jamun (1 order) from Spice Garden restaurant. Order total was ₹485. When the delivery arrived, I received Veg Pulao instead of Chicken Biryani. I am vegetarian — wait no, I am non-vegetarian and I specifically ordered chicken. Please arrange for the correct item or process a refund for the biryani (₹220).',
    channel: 'APP',
    customerId: 'cust-002',
    subCategoryName: 'Wrong Item Delivered',
    orderId: 'ORD-654321',
    tags: ['wrong-item', 'refund-requested', 'in-progress'],
    firstResponseDeadline: new Date(Date.now() + 1000 * 60 * 30).toISOString(),
    resolutionDeadline: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    customerPhone: '+91 87654 32109',
    customerEmail: 'priya.nair@gmail.com',
    totalTickets: 1,
  },
  'TKT-2024-003': {
    ...MOCK_TICKETS[2],
    description: 'I raised a refund request 7 days ago (Ticket #TKT-2024-198) for a cancelled order. The refund amount of ₹650 was supposed to be credited within 5-7 business days. Today is day 7 and I still have not received the refund. Please check immediately. My UPI ID is amitpatel@okaxis.',
    channel: 'WHATSAPP',
    customerId: 'cust-003',
    subCategoryName: 'Refund Delayed',
    orderId: 'ORD-112233',
    tags: ['refund', 'escalated', 'sla-breach'],
    firstResponseDeadline: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    resolutionDeadline: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    customerPhone: '+91 76543 21098',
    customerEmail: null,
    totalTickets: 5,
  },
};

export const MOCK_ACTIVITIES: Record<string, TicketActivity[]> = {
  'TKT-2024-001': [
    {
      id: 'act-001-1',
      activityType: 'COMMENT',
      content: 'I placed an order at 6:30 PM and it is now 9:20 PM. My order has not arrived and the delivery partner is unreachable. This is absolutely unacceptable!',
      isInternal: false,
      actorId: 'cust-001',
      actorType: 'CUSTOMER',
      actorName: 'Rahul Sharma',
      createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    },
    {
      id: 'act-001-2',
      activityType: 'STATUS_CHANGE',
      content: 'Ticket created and assigned priority URGENT due to delivery delay',
      isInternal: true,
      actorId: 'system',
      actorType: 'AGENT',
      actorName: 'System',
      createdAt: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    },
  ],
  'TKT-2024-002': [
    {
      id: 'act-002-1',
      activityType: 'COMMENT',
      content: 'I received the wrong item! I ordered Chicken Biryani but got Veg Pulao. This is really disappointing. Please help me get a refund or the correct item.',
      isInternal: false,
      actorId: 'cust-002',
      actorType: 'CUSTOMER',
      actorName: 'Priya Nair',
      createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    },
    {
      id: 'act-002-2',
      activityType: 'COMMENT',
      content: 'Hi Priya, I\'m so sorry for the inconvenience. I can see your order clearly shows Chicken Biryani. I\'m checking with the restaurant right now. Could you please confirm if you\'d prefer a re-delivery or a refund to your original payment method?',
      isInternal: false,
      actorId: 'agent-me',
      actorType: 'AGENT',
      actorName: 'You (Arjun)',
      createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    },
    {
      id: 'act-002-3',
      activityType: 'COMMENT',
      content: 'Checked with restaurant — they confirm it was a packing error on their end. Customer can choose refund or re-delivery. Restaurant has agreed to prioritize.',
      isInternal: true,
      actorId: 'agent-me',
      actorType: 'AGENT',
      actorName: 'You (Arjun)',
      createdAt: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    },
    {
      id: 'act-002-4',
      activityType: 'COMMENT',
      content: 'I would prefer a refund please. The food has already gone cold by the time I discovered the wrong item.',
      isInternal: false,
      actorId: 'cust-002',
      actorType: 'CUSTOMER',
      actorName: 'Priya Nair',
      createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    },
  ],
  'TKT-2024-003': [
    {
      id: 'act-003-1',
      activityType: 'COMMENT',
      content: 'Where is my refund? It has been 7 days. I need this money back urgently.',
      isInternal: false,
      actorId: 'cust-003',
      actorType: 'CUSTOMER',
      actorName: 'Amit Patel',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    },
    {
      id: 'act-003-2',
      activityType: 'COMMENT',
      content: 'Dear Amit, I sincerely apologize for the delay. I can see the refund was initiated on our end 7 days ago. Let me escalate this to our payments team for immediate investigation.',
      isInternal: false,
      actorId: 'agent-other',
      actorType: 'AGENT',
      actorName: 'Sneha (Agent)',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 47).toISOString(),
    },
    {
      id: 'act-003-3',
      activityType: 'STATUS_CHANGE',
      content: 'Ticket escalated to payments team. Refund tracking ID: REF-2024-88901',
      isInternal: true,
      actorId: 'agent-other',
      actorType: 'AGENT',
      actorName: 'Sneha (Agent)',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 46).toISOString(),
    },
    {
      id: 'act-003-4',
      activityType: 'COMMENT',
      content: 'I am still waiting! This is the worst service I have experienced. I am going to file a consumer complaint if this is not resolved today.',
      isInternal: false,
      actorId: 'cust-003',
      actorType: 'CUSTOMER',
      actorName: 'Amit Patel',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
  ],
};

export const MOCK_SUGGESTIONS: ResolutionSuggestion[] = [
  {
    title: 'Full Refund — Standard Resolution',
    content: 'Dear [Customer Name],\n\nI sincerely apologize for this inconvenience. I have processed a full refund of ₹[AMOUNT] to your original payment method. The amount will reflect within 3-5 business days for card payments or within 24 hours for UPI/wallet transactions.\n\nAs a goodwill gesture, I have also added ₹50 credit to your account for use on your next order.\n\nPlease do not hesitate to contact us if you need further assistance.\n\nWarm regards,\nSupport Team',
    confidence: 0.94,
  },
  {
    title: 'Re-delivery Offer',
    content: 'Dear [Customer Name],\n\nI apologize for the mix-up with your order. I have arranged for the correct item to be delivered to you as a priority. Your re-delivery is scheduled within the next 45-60 minutes at no additional charge.\n\nThe delivery partner will call you before arriving. Please keep your phone accessible.\n\nSorry again for the inconvenience — we are taking steps to prevent this from recurring at this restaurant.',
    confidence: 0.87,
  },
  {
    title: 'Partial Refund + Credit',
    content: 'Dear [Customer Name],\n\nThank you for bringing this to our attention. I have processed a partial refund of ₹[AMOUNT] for the affected item(s) along with ₹100 SupportHub credit as compensation for the inconvenience caused.\n\nThe refund will be credited within 3-5 business days. The credit is immediately available in your wallet and valid for 30 days.\n\nWe value your patronage and assure you of better service going forward.',
    confidence: 0.76,
  },
];

export const MOCK_METRICS: DashboardMetrics = {
  myOpenTickets: 4,
  myUrgentTickets: 2,
  unassignedTickets: 5,
  slaBreachedTickets: 3,
  resolvedToday: 7,
  avgFirstResponseMinutes: 18,
  teamOpenTickets: 23,
  teamResolvedToday: 19,
  myTicketsThisWeek: 31,
  satisfactionScore: 4.2,
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'SLA_BREACH',
    title: 'SLA Breached — TKT-2024-001',
    message: 'Ticket for Rahul Sharma has breached SLA deadline. Immediate action required.',
    ticketNumber: 'TKT-2024-001',
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'TICKET_ASSIGNED',
    title: 'Ticket assigned to you',
    message: 'TKT-2024-007 has been assigned to you by Team Lead.',
    ticketNumber: 'TKT-2024-007',
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'CUSTOMER_REPLY',
    title: 'Customer replied — TKT-2024-002',
    message: 'Priya Nair has replied: "I would prefer a refund please..."',
    ticketNumber: 'TKT-2024-002',
    createdAt: new Date(Date.now() - 1000 * 60 * 26).toISOString(),
    isRead: false,
  },
  {
    id: 'notif-4',
    type: 'SLA_WARNING',
    title: 'SLA Warning — TKT-2024-010',
    message: 'Ticket TKT-2024-010 is approaching SLA deadline in 30 minutes.',
    ticketNumber: 'TKT-2024-010',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    isRead: true,
  },
  {
    id: 'notif-5',
    type: 'TICKET_ESCALATED',
    title: 'Ticket escalated',
    message: 'TKT-2024-003 has been escalated to the payments team.',
    ticketNumber: 'TKT-2024-003',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    isRead: true,
  },
];

export const MOCK_CUSTOMER_PROFILES: Record<string, CustomerProfile> = {
  'cust-001': {
    id: 'cust-001',
    name: 'Rahul Sharma',
    phone: '+91 98765 43210',
    email: null,
    totalTickets: 3,
    openTickets: 2,
    joinedAt: '2023-06-15T00:00:00Z',
    preferredLanguage: 'en',
    lastOrderAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  'cust-002': {
    id: 'cust-002',
    name: 'Priya Nair',
    phone: '+91 87654 32109',
    email: 'priya.nair@gmail.com',
    totalTickets: 1,
    openTickets: 1,
    joinedAt: '2024-01-10T00:00:00Z',
    preferredLanguage: 'en',
    lastOrderAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  'cust-003': {
    id: 'cust-003',
    name: 'Amit Patel',
    phone: '+91 76543 21098',
    email: null,
    totalTickets: 5,
    openTickets: 1,
    joinedAt: '2022-11-20T00:00:00Z',
    preferredLanguage: 'hi',
    lastOrderAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
};
